name: Unit Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  UnitTests:
    runs-on: macos-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec fastlane test
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults/GitHubActionsExample.xcresult
        if: success() || failure()